services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
  db:
    build: ./database
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: