ALTER TABLE "Country" ADD COLUMN "population" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Country" ADD COLUMN "currency" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Country" ADD COLUMN "currencyName" TEXT NOT NULL DEFAULT '';
